name: ✏️ Update a Competition
description: Request an update to an existing tech competition in Algeria.
title: "[Update Event] "
labels: [event update]
body:
  - type: input
    id: current_name
    attributes:
      label: Current Event Name
      placeholder: "e.g., Hack the South"
    validations:
      required: true

  - type: input
    id: changes
    attributes:
      label: What needs to be updated?
      placeholder: "e.g., Updated link, new date, new organizer"
    validations:
      required: true

  - type: input
    id: proof
    attributes:
      label: Source or Proof of Change (optional but recommended)
      placeholder: "https://example.com/new-info"
    validations:
      required: false
